### ISSUE TITLE
Implementing Impersonation

### ISSUE THREAD

**Issue by bokobza** [richardlawley/cloudstack.net#3]
Hi,
I'm keen to implement Impersonation in the SDK but I'm not too sure how to proceed.

1. First off, a client consuming the SDK can **already** add impersonation to a request just by assigning the Account and DomainId properties that are present in the objects that support Impersonation such as DeployVirtualMachine:

``` csharp
    var deployRequest = new DeployVirtualMachineRequest
    {
        ZoneId = myZoneId,
        TemplateId = myZoneId,
        //...
        // the following are all that's required for impersonation 
        Account = account,
        DomainId = domainId
    };
```

2. The supportImpersonation parameter in APIRequest's constructor is going to be hard to assign for the generated classes. Is that just some code left behind from the original SDK?

3. Unfortunately, the presence of Account and DomainId in the command arguments is not sufficient to conclude that the command supports Impersonation, as sometimes these arguments are used as filters in the API (especially for list[xxx] methods). See more details on these inconsistencies [here](https://cwiki.apache.org/confluence/display/CLOUDSTACK/API+changes). 
Based on that, we can't even set supportImpersonation = true based on the presence of Account and DomainId.

I feel the only way for consumers of the SDK to **explicitly** impersonate a request would be to have a hard-coded list of commands that support Impersonation.

What do you think?

**Comment by richardlawley** [comment]
The SupportsImpersonation stuff is indeed something I inherited from the original SDK - I have not used this myself nor made any effort on it.  I wasn't even aware of what the impersonation implementation was until I just looked it up - my own application has me storing client keys anyway so I just use those instead of impersonating.  The page you linked to also suggests that they are planning to deprecate that method of using impersonation.

As you mention, you can already perform the impersonation for requests which support it - what functionality are you trying to get by obtaining a list of APIs which support it?

**Comment by bokobza** [comment]
Hi Richard,
I was trying to help the user explicitly decide to impersonate.
On second thought, since the API is a bit dodgy in this regard, I think it's best to just leave it as it is (and the consumer of the SDK can just use Account and DomainId to impersonate) rather than try to be too clever. Thank you for replying :-)

**Comment by richardlawley** [comment]
No problem.  If this gets addressed by the CS people, and especially if there's a way for my scripts to find the commands which support impersonation, I'll reconsider this.
